name: Enomdle Server Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # 1. 자바 세팅
      - uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      # 2. 빌드
      - run: chmod +x gradlew
      - run: ./gradlew clean build -x test

      # 3. 도커 로그인 & 빌드 & 푸시
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          # ★ 여기가 바뀌었습니다! (hackathon-server -> enomdle-server)
          tags: ${{ secrets.DOCKER_USERNAME }}/enomdle-server:latest

      # 4. EC2 접속 및 배포
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            # 기존 서버 중지 및 삭제
            sudo docker stop my-server || true
            sudo docker rm my-server || true
            
            # ★ 이미지 다운로드 이름 변경!
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/enomdle-server:latest
            
            # ★ 실행 명령어도 이름 변경!
            sudo docker run -d --name my-server -p 8080:8080 \
              -e DB_URL=${{ secrets.DB_URL }} \
              -e DB_USERNAME=${{ secrets.DB_USERNAME }} \
              -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
              ${{ secrets.DOCKER_USERNAME }}/enomdle-server:latest
            
            sudo docker image prune -f